version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/media:/app/media
    environment:
      - YOUTUBE_KEY=${YOUTUBE_KEY:-}
      - PROXY_URL=${PROXY_URL:-}
      - DEBUG=${DEBUG:-false}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - MEDIA_DIR=media
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT:-30}
      - DOWNLOAD_TIMEOUT=${DOWNLOAD_TIMEOUT:-60}
      - RATE_LIMIT=${RATE_LIMIT:-100}
    env_file:
      - ./backend/.env
    networks:
      - appnet
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - appnet
networks:
  appnet:
    driver: bridge 